### ISSUE TITLE
Auto new hackernewsletter detector to trigger main build

### ISSUE THREAD

**Issue by LucasVos** [bitfox-git/hackernewspaper#3]
The current hackernewsletter Github action is run manually, after updating the issue variable in the settings.  
Normally, a news hackernewletter is send around friday.

Develop a second, scheduled, Github action, that tries to determine if a new newsletter is already published and if so, update the issue-variable in settings+trigger the main Github build action. Schedule it to run at friday night.

**Comment by DvdPlaat** [comment]
Resolved by #5
